Add planar trifocal tensor
borglab/gtsam pull request #1094
Opened 2022-02-09 05:24 UTC by Hal-Zhaodong-Yang

This PR adds the following:

1. Add `TrifocalTensor2.[h|cpp]`,  which declare and define planar trifocal tensor class `TrifocalTensor2`. 
2. Create `TrifocalTensor2` constructors from bearing measurements and bearing measurements expressed in projective coordinates.
3. Create class method `transform` to find a measurement in the first view using measurements from second and third views.
4. Add unit test `testTrifocalTensor2.cpp`, which tests the constructed planar trifocal tensor.
5. Test the `transform` method by comparing a set of ground-true bearing measurements with an estimated bearing measurements.

2022-02-09 15:33 UTC, dellaert commented on gtsam/geometry/tests/testTrifocalTensor2.cpp
> +#include <iostream>
comment block missing

2022-02-09 15:35 UTC, dellaert requested changes
We need to thin k about the nonlinear case before reviewing

2022-02-09 16:00 UTC, dellaert commented on gtsam/geometry/tests/testTrifocalTensor2.cpp
> +TEST(TrifocalTensor2, transform) {
add a comment

2022-02-09 16:00 UTC, dellaert commented on gtsam/geometry/tests/testTrifocalTensor2.cpp
> +  TrifocalTensor2 T(measurement_u, measurement_v, measurement_w);
Change to a "named constructor", `static FromBearingMeasurements()`

2022-02-09 16:00 UTC, dellaert commented on gtsam/geometry/tests/testTrifocalTensor2.cpp
> +  for (unsigned int i = 0; i < measurement_u.size(); i++) {
size_t

2022-02-09 16:00 UTC, dellaert commented on gtsam/geometry/tests/testTrifocalTensor2.cpp
> +        T.transform(measurement_v[i], measurement_w[i]);
comment that this is important and is being tested

2022-02-09 16:00 UTC, dellaert commented on gtsam/geometry/tests/testTrifocalTensor2.cpp
> +  landmarks.push_back(Point2(2.0, 0.5));
no copy/paste!

2022-02-09 16:00 UTC, dellaert commented on gtsam/geometry/tests/testTrifocalTensor2.cpp
> +  landmarks.push_back(Point2(2.0, 0.5));
copy/paste !!!!!??????

2022-02-09 16:00 UTC, dellaert commented on gtsam/geometry/tests/testTrifocalTensor2.cpp
> +  TrifocalTensor2 T(measurement_u, measurement_v, measurement_w);
Have a test for this method, and explain where the ground truth comes from!

2022-02-09 16:00 UTC, dellaert commented on gtsam/geometry/tests/testTrifocalTensor2.cpp
> +  Matrix2 exp_trifocal_tensor_mat0;
Annotate this with //regression

2022-02-09 17:12 UTC, dellaert commented
Oh, and, BTW, CI seems to fail. Please do "make check" before doing a push to gtsam repo. As an aside, every push triggers CI, so please don't push every commit - push once you both are satisfied with changes. A development like this might be better done in a fork

2023-11-10 18:04 UTC, varunagrawal commented
@Hal-Zhaodong-Yang do you intend to continue working on this?

2026-08-12 01:58 UTC, dellaert commented
I updated the PR branch to the latest `develop` (`8b67dc5719`) and pushed the resulting history directly to `Hal-Zhaodong-Yang/gtsam:trifocal`.

Validation after the merge:

- `make -j6 testTrifocalTensor2.run`: passed
- `make -j6 check`: 300/300 tests passed
- `git diff --check`: clean

I also had Codex review the updated implementation against current repository guidance and the existing `EssentialMatrixFactor*`, `EssentialMatrixConstraint`, `FundamentalMatrix`, `TripleF`, and `EpipolarTransfer` APIs. The inline comments in the following review are findings generated by **Codex**.

2026-08-12 01:58 UTC, dellaert reviewed
## Codex review

These inline findings were generated by **Codex** after updating the PR to the latest `develop`. They focus on numerical correctness and integration with the current geometry API. `TrifocalTensor2` is adjacent to, but not a duplicate of, the existing essential/fundamental-matrix factors: it models three P¹ observations in a planar world, while `EssentialMatrixFactor*` and `TripleF` operate on ordinary P² image geometry.

2026-08-12 01:58 UTC, dellaert commented on gtsam/geometry/TrifocalTensor2.cpp
> +  svd(A, U, S, V);
**Codex review — P1:** The estimator always accepts the final singular vector, even when the correspondence matrix has rank below seven. Repeated or otherwise degenerate correspondences therefore return an arbitrary tensor. Please use the existing `DLT()` helper, inspect its returned rank, and reject rank-deficient systems; add a repeated/degenerate-correspondence test.

2026-08-12 01:58 UTC, dellaert commented on gtsam/geometry/TrifocalTensor2.cpp
> +          A(row, 4 * i + 2 * j + k) = u[row](i) * v[row](j) * w[row](k);
**Codex review — P1:** Each projective input may be scaled independently, but that scale multiplies this DLT row and changes its least-squares weight for noisy or overdetermined data. Normalize each Kronecker row (and reject zero projective coordinates) so `FromProjectiveBearingMeasurements` is genuinely invariant to homogeneous input scale. Please add a noisy rescaling test.

2026-08-12 01:58 UTC, dellaert commented on gtsam/geometry/TrifocalTensor2.h
> +  TrifocalTensor2() : matrix0_(Matrix2::Zero()), matrix1_(Matrix2::Zero()) {}
**Codex review — P2:** A homogeneous tensor must have nonzero scale, but this default constructs the zero tensor. It transfers to the invalid projective point `(0,0)` and silently produces a zero-angle `Rot2`. Please delete/restrict the default constructor or provide a documented valid canonical value, and reject a zero tensor in the matrix constructor.

2026-08-12 01:58 UTC, dellaert commented on gtsam/geometry/TrifocalTensor2.h
> +class GTSAM_EXPORT TrifocalTensor2 {
**Codex review — P2:** This is a new public geometric relation but it is absent from `gtsam/geometry/geometry.md` and `gtsam/geometry/cameras.i`. Please document and wrap it alongside `FundamentalMatrix`, explicitly explaining that this tensor transfers three planar P¹ bearings and is not a replacement for `EssentialMatrixFactor*`, `EssentialMatrixConstraint`, or the P² `TripleF`/`EpipolarTransfer` utility.

2026-08-12 16:35 UTC, dellaert commented
codex: This adds a planar trifocal tensor type, construction and transformation APIs, and associated unit tests. Labeled enhancement because it introduces a new geometry capability.

2026-08-19 03:18 UTC, dellaert commented
@akshay-krishnan do we need this for GTSFM?

2026-08-19 03:29 UTC, akshay-krishnan commented
> @akshay-krishnan do we need this for GTSFM?

No plans to use it. This was for line features. But this implementation is for bearing measurements in 2D, so needs more work for lines. And we dont plan on having line features in gtsfm anyway.

2026-08-19 16:31 UTC, dellaert commented
Ok. Do you want to close it? Or address comments and merge it?

2026-08-23 14:51 UTC, dellaert commented
Closing as no-one seems to have cycles to address comments.

2026-08-23 14:51 UTC, closed without merging