Add vcpkg ci
borglab/gtsam pull request #1413
Opened 2023-01-24 14:54 UTC by talregev

Add vcpkg ci. Fix #672

I try to minimize the changes as much as possible. 
I delete the `FindTBB.cmake`. I think it old file, and the default of the cmake is working well also on your tests. 
I also add to your workflow, that it will do test only when doing PR to devel and push to devel, as it your most use cases. 
Also I add concurrency section, that it cancel automatic other check when you push to your PR another commit before the other check is not finish. It not doing that when you merge or push to devel, because each change there is important. 
It useful to shave resource and time for check your PRs.

Also there some bugs that I encounter that I think needed to fix in other PRs. 
This PR already have many things to discuss. 

This is start of infrastructure how to use vcpkg and can also extended (in other PRs). For example to publish binaries in the PR itself, that it can downloaded and test them externally. 
Maybe other use cases you want to test.
My moto is to compile as much as possible in one test (and hopefully to run the tests themself), to know much quicker to the problem when you doing a PR.

gtsam bugs:
1. windows gtsam_unstable
```
gtsam.lib(gtsam.dll) : error LNK2005: "public: __cdecl std::map<unsigned __int64,unsigned __int64,struct std::less<unsigned __int64>,class std::allocator<struct std::pair<unsigned __int64 const ,unsigned __int64> > >::~map<unsigned __int64,unsigned __int64,struct std::less<unsigned __int64>,class std::allocator<struct std::pair<unsigned __int64 const ,unsigned __int64> > >(void)" (??1?$map@_K_KU?$less@_K@std@@V?$allocator@U?$pair@$$CB_K_K@std@@@2@@std@@QEAA@XZ) already defined in LPInitSolver.obj [D:\a\gtsam\gtsam\build\gtsam_unstable\gtsam_unstable.vcxproj]
     Creating library D:/a/gtsam/gtsam/build/lib/Release/gtsam_unstable.lib and object D:/a/gtsam/gtsam/build/lib/Release/gtsam_unstable.exp
```
2. Errors on tests:
```
/home/runner/work/gtsam/gtsam/gtsam/hybrid/tests/testHybridEstimation.cpp:221:8: error: ‘bitset’ is not a member of ‘std’
  221 |   std::bitset<K - 1> seq = x;
```
```
/home/runner/work/gtsam/gtsam/gtsam/hybrid/tests/testHybridEstimation.cpp:221:22: error: ‘seq’ was not declared in this scope
  221 |   std::bitset<K - 1> seq = x;
      |                      ^~~
```

3. windows python
```
LINK : fatal error LNK1149: output filename matches input filename 'D:\a\gtsam\gtsam\build\lib\Release\gtsam.lib' [D:\a\gtsam\gtsam\build\python\gtsam_py.vcxproj]
```

2023-01-24 18:29 UTC, dellaert commented
Cool, thanks for contributing !!! Workflow is failing for another reason, most likely OOM. I'm a bit swamped with getting boost out of 4.3 to land something like this right now, and I'll also like to learn a bit about this rather substantial PR. Can we have a call about this over the weekend or early next week?

2023-01-24 18:41 UTC, talregev commented
> Cool, thanks for contributing !!! Workflow is failing for another reason, most likely OOM. I'm a bit swamped with getting boost out of 4.3 to land something like this right now, and I'll also like to learn a bit about this rather substantial PR. Can we have a call about this over the weekend or early next week?

Yes, we can do on the weekend. 
Can you approve my PR that it just run the tests?

2023-01-24 18:56 UTC, dellaert commented
> > Cool, thanks for contributing !!! Workflow is failing for another reason, most likely OOM. I'm a bit swamped with getting boost out of 4.3 to land something like this right now, and I'll also like to learn a bit about this rather substantial PR. Can we have a call about this over the weekend or early next week?
> 
> Yes, we can do on the weekend. Can you approving review in my PR that it just run the tests?

Will do! Send an email to fd27@gatech.edu to set up a time :-)

2023-01-24 18:57 UTC, dellaert requested changes
Blocking a merge for now until I understand completely, but this looks cool!

2023-01-24 18:59 UTC, talregev commented
> > > Cool, thanks for contributing !!! Workflow is failing for another reason, most likely OOM. I'm a bit swamped with getting boost out of 4.3 to land something like this right now, and I'll also like to learn a bit about this rather substantial PR. Can we have a call about this over the weekend or early next week?
> > 
> > 
> > Yes, we can do on the weekend. Can you approving review in my PR that it just run the tests?
> 
> Will do! Send an email to [fd27@gatech.edu](mailto:fd27@gatech.edu) to set up a time :-)

Just type your comment here when you have time. If we need more interactive, I can send you an email :)

2023-01-24 19:12 UTC, dellaert commented
> > Will do! Send an email to [fd27@gatech.edu](mailto:fd27@gatech.edu) to set up a time :-)
> 
> Just type your comments here when you have time. If we need more interactive, I will send you an email :) Thanks!

The email path is also so I can set up an invite.

2023-04-30 12:10 UTC, talregev commented
@dellaert Are you still interested in this changes?

2023-04-30 15:16 UTC, talregev commented
All the tests are passing:
https://github.com/talregev/gtsam/pull/1

2023-06-13 04:58 UTC, talregev commented
New things I develop from last time:
- All os compile with ninja compilation. 
- Tests compile and run on linux and macos.

Bugs:
- On Windows it needed tbb debug on release compilation.
- Test don't compile on windows. missing symbols. 
- One test is fail on run time, so I comment it out.

2023-06-17 11:27 UTC, talregev commented
@varunagrawal
Can you take a look on my PR?

2023-06-18 05:15 UTC, varunagrawal commented
@talregev I'm trying to fix #1541 before tackling this PR. Apologies for the day.

2023-06-18 05:16 UTC, talregev commented
I also got this error. Not sure how to fix it. You can see the error above

2023-06-20 13:20 UTC, varunagrawal commented
> I also got this error. Not sure how to fix it. You can see the error above

Yup it's the same issue. Once we debug and fix that, I'll immediately review your PR. Thank you again for the amazing contribution and your patience.

2023-06-26 18:44 UTC, varunagrawal commented
Hi @talregev. Is there any reason you're pushing updates to this PR? I figured we would wait till we got #1553 working before continuing on this. If you can help the effort on #1553, we would really appreciate it. :)

2023-06-26 19:01 UTC, talregev commented
> Hi @talregev. Is there any reason you're pushing updates to this PR? I figured we would wait till we got #1553 working before continuing on this. If you can help the effort on #1553, we would really appreciate it. :)

@varunagrawal I was testing the cache. Also found some bugs. So I did a ci driven develop. So there is many pushes. 
Now it working. I will try to help you with #1553
What it missing?

2023-10-12 05:53 UTC, talregev commented
@varunagrawal This PR is ready for review.
The tests fail because of their correctness. I don't have the knowledge to solve them. Can you help? 
Other wise is ready for review and I will happy to hear your comments.

2023-12-06 20:34 UTC, talregev commented
@dellaert This PR is ready for review.
Can you take a look?

2025-06-05 06:27 UTC, talregev commented
@dellaert 
Is this PR is still relevant for you?

2025-06-06 18:26 UTC, closed without merging