Fixing stack overflow issue for large tree
borglab/gtsam pull request #1441
Opened 2023-02-05 22:12 UTC by wanmeihuali

This is a patch for [Issue-1433](https://github.com/borglab/gtsam/issues/1433). 
- The root cause for [Issue-1433](https://github.com/borglab/gtsam/issues/1433) is that smart pointers, especially shared_ptr, is not a good choice to manage data structures such as tree or graph, because they can easily cause stack overview during destruction. 
- In this patch, we manually release the root node of the tree data structure during a BFS when a destructor is called. In this way, the previous recursive release for tree nodes is now sequential. The algorithm is carefully designed so that it won't break the edges between nodes, and in this way keeps the same behavior even when some tree nodes are held by extra codes.
- We tested the modified code with the given example in [Issue-1433], and the issue is fixed with the patch.
- Does it solve all similar issues? We only fixed the three tree data structures we used in our use case(which is a bit more complex version of the bug reproduction code in the issue) in this patch. Considering there are tons of similar tree data structures in Gtsam, it is likely that a similar issue will happen again when other people use other tree data structures, and these issues should be able to be fixed in a similar way. However, fixing all data structures is a large work and we won't do it in this patch.
- To fully get rid of the stack overflow issue, one suggestion is to adopt some garbage collection library and have a global replacement for shared_ptr/make_shared. Of course, it is also necessary to make sure the garbage collection library does not use any recursive implementation. In this way, all similar issues will be solved without a large modification of the existing code, Considering that the garbage collection solution may cause some performance loss, a compiling flag can be used to control whether to use a smart pointer or garbage collection and let the user make the decision based on their use case.

2023-02-05 22:22 UTC, dellaert commented
Thanks @wanmeihuali !!! @ProfFan let's wait to run CI here as I'm trying to debug some other issues now.

2023-02-06 20:56 UTC, ProfFan commented
CI is failing, @wanmeihuali could you rebase to develop and see if it still fails?

2023-02-06 21:01 UTC, wanmeihuali commented
Yep, seems like a network or dep version issue. Just merged the latest develop. XD

2023-02-06 23:07 UTC, dellaert commented
Very interesting! Note, there are not tons of more tree data structures in gtsam, these are really the most important ones :-). I must say, though, I don’t fully understand the mechanism yet. Pushing the nodes into the BFS queue is one thing, but I’m assuming there is also an assumption that something will happen when the queue is deleted? That’s not really explained.

I also don’t understand why you do a clear on nodes_ first. Will  that not be a problem if reference counts go to zero? You probably have very good answer is for all these questions, it’s just a matter of getting them into the code comments for future reference :-)

2023-02-07 00:10 UTC, wanmeihuali commented
> Very interesting! Note, there are not tons of more tree data structures in gtsam, these are really the most important ones :-). I must say, though, I don’t fully understand the mechanism yet. Pushing the nodes into the BFS queue is one thing, but I’m assuming there is also an assumption that something will happen when the queue is deleted? That’s not really explained.
> 
> I also don’t understand why you do a clear on nodes_ first. Will that not be a problem if reference counts go to zero? You probably have very good answer is for all these questions, it’s just a matter of getting them into the code comments for future reference :-)

Yep it's quite tricky, I write some mermaid show a tree is released by this algorithm. The releasing is actually happening when a node is popped from the queue and then leaves the scope. For BFS, the queue is always empty after all. @dellaert 
Initial state:
```mermaid
graph TD
    T[Tree Data Structure]
    T-->A((A))
    A-->B((B))
    B-->D((D))
    B-->E((E))
    D-->G((G))
    Z[Context]
    Z--hold by other data structure-->D
```
Expect behavior:
- A, B, and E are released without recursive.
- D and G are not released, and G is still the child of D.

```mermaid
graph TD
    Q[BFS Queue]
    T[Tree Data Structure]
    T-->A((A))
    A-->B((B))
    B-->D((D))
    B-->E((E))
    D-->G((G))
    Z[Context]
    Z--hold by other data structure-->D
```

```mermaid
graph TD
    Q[BFS Queue]
    T[Tree Data Structure]
    Q==push into queue==>A((A))
    T-.set to nullptr.->A
    A-->B((B))
    B-->D((D))
    B-->E((E))
    D-->G((G))
    Z[Context]
    Z--hold by other data structure-->D
```


```mermaid
graph TD
    Q[BFS Queue]
    T[Tree Data Structure]
    Q-->A((A))
    A-->B((B))
    B-->D((D))
    B-->E((E))
    D-->G((G))
    Z[Context]
    Z--hold by other data structure-->D
```

```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    Q-.popping front.->A((A))
    Z==getting front==>A
    A-->B((B))
    B-->D((D))
    B-->E((E))
    D-->G((G))
    Z--hold by other data structure-->D
```

```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    Z-->A((A))
    A-->B((B))
    Q==BFS: adding children to queue==>B
    B-->D((D))
    B-->E((E))
    D-->G((G))
    Z--hold by other data structure-->D
```

```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    Z-.leaving scope-.->A((A, ref=0))
    A-->B((B))
    Q-->B
    B-->D((D))
    B-->E((E))
    D-->G((G))
    Z--hold by other data structure-->D
```


```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    A((A))-.A get released.->B((B))
    style A stroke:#333,stroke-width:4px
    Q--holds B so B will not be released recursively-->B
    B-->D((D))
    B-->E((E))
    D-->G((G))
    Z--hold by other data structure-->D
```


```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    Q-.popping front.->B((B))
    Z==getting front==>B
    B-->D((D))
    B-->E((E))
    D-->G((G))
    Z--hold by other data structure-->D
```


```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    Z-->B
    B((B))-->D((D))
    B-->E((E))
    D-->G((G))
    Q==BFS: adding children to queue==>D
    Q==BFS: adding children to queue==>E
    Z--hold by other data structure-->D
```


```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    Z-.leaving scope.->B
    B((B, ref=0))-->D((D))
    B-->E((E))
    D-->G((G))
    Q==BFS: adding children to queue==>D
    Q==BFS: adding children to queue==>E
    Z--hold by other data structure-->D
```


```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    B((B))-.B released.->D((D))
    style B stroke:#333,stroke-width:4px
    B-.B released.->E((E))
    D-->G((G))
    Q-->D
    Q-->E
    Z--hold by other data structure-->D
```


```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    D((D))-->G((G))
    Q-.pop front.->D
    Q-->E((E))
    Z--hold by other data structure-->D
    Z==getting front==>D
```

```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    D((D))-->G((G))
    Q-->E((E))
    Q==BFS: adding children to queue==>G
    Z--hold by other data structure-->D
    Z-->D
```

```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    D((D, ref=1))-->G((G))
    Q-->E((E))
    Q-->G
    Z--hold by other data structure-->D
    Z-.leaving scope.->D
```

```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    D((D))-->G((G))
    Q-.pop front.->E((E))
    Z==getting front==>E
    Q-->G
    Z--hold by other data structure-->D
```


```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    D((D))-->G((G))
    Z-.leaving scope.->E((E, ref=0))
    style E stroke:#333,stroke-width:4px
    Q-->G
    Z--hold by other data structure-->D
```

```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    D((D))-->G((G))
    Q-.pop front.->G
    Z==getting front==>G
    Z--hold by other data structure-->D
```

```mermaid
graph TD
    Q[BFS Queue]
    Z[Context]
    D((D))-->G((G, ref=1))
    Z-.leaving scope.->G
    Z--hold by other data structure-->D
```

2023-02-07 01:12 UTC, dellaert commented
Oh, that helps a lot! I will approve the PR, but I will also leave some  comments as to where you could add some of that explanation in the code.

2023-02-07 01:19 UTC, dellaert requested changes
Amazing!! I do feel strongly that things are not cluttering the header if possible, so will “request changes” for now and re-review on push…

2023-02-07 01:19 UTC, dellaert commented on gtsam/inference/BayesTree.h
> +#include <queue>
I would prefer that we add include headers and the code in the -inl.h file, rather than in this .h file.

2023-02-07 01:19 UTC, dellaert commented on gtsam/inference/BayesTree.h
> +      nodes_.clear();  // clear the map manually, as we cannot control the order of destruction in the map
Add comment to say this reduces the ref count but not to zero yet

2023-02-07 01:19 UTC, dellaert commented on gtsam/inference/BayesTree.h
> +    ~BayesTree() {
Add function level comment with link to this PR for the cool graphs…

2023-02-07 01:19 UTC, dellaert commented on gtsam/inference/BayesTree.h
> +        }
Add a comment here to say share_ptr will drop to zero when current goes out of scope

2023-02-07 01:19 UTC, dellaert commented on gtsam/inference/ClusterTree.h
> +#include <queue>
All same comments for this file

2023-02-07 01:19 UTC, dellaert commented on gtsam/inference/EliminationTree.h
> +#include <queue>
And for this file

2023-02-08 03:24 UTC, dellaert approved these changes
Very cool, a great addition to enable GTSAM to do large scale inference!

2023-02-08 13:45 UTC, ProfFan approved these changes
Thanks @wanmeihuali :)

2023-02-09 03:07 UTC, merged

2023-05-05 14:47 UTC, ShuangLiu1992 commented
I wonder if the same fix should be applied to BayesTreeCliqueBase?

2023-05-05 14:53 UTC, ShuangLiu1992 commented
current develop branch seems to have missed this commit for gtsam/inference/BayesTreeCliqueBase.h

https://github.com/wanmeihuali/gtsam/commit/1d06f1e7667d3f9c9761161cbbf9e47aa3955559

2023-05-05 15:36 UTC, wanmeihuali commented
> current develop branch seems to have missed this commit for gtsam/inference/BayesTreeCliqueBase.h
> 
> [wanmeihuali@1d06f1e](https://github.com/wanmeihuali/gtsam/commit/1d06f1e7667d3f9c9761161cbbf9e47aa3955559)

@ShuangLiu1992  Yep, As I mentioned I only fixed the issue in my use case... Because Clique Tree is much smaller than the original tree, it did not trigger stack overflow for my case.
You may ask @ProfFan and @dellaert for another patch.

2023-05-07 04:37 UTC, wanmeihuali commented
@ShuangLiu1992 I just got some time to check it, gtsam/inference/BayesTreeCliqueBase.h is the base class for the node in BayesTree, so the patch should already fix the issue if you are using BayesTree.h... You can check the image I attached for how it works. If you still got a stackoverflow, maybe you are using another tree data structure with BayesTreeCliqueBase?

2023-05-07 10:19 UTC, ShuangLiu1992 commented
@wanmeihuali Thanks for taking the time to check. I will double check. On some platforms we are constrained with a stack size of 1mb so the stackover flow might have came from somewhere else in the library. Debug builds are too big to fit on the target machine and Release builds crashes without giving any useful information.....

2023-05-24 05:27 UTC, ProfFan commented
1MB of stack is a bit too small for current GTSAM but you can try changing some stack variables used to `unique_ptr`s