Fix Windows Tests
borglab/gtsam pull request #1553
Opened 2023-06-21 21:36 UTC by varunagrawal

My attempt at fixing #1541.

1. Add fix for compilation in Visual Studio. This seems to be a weird issue with how `size_t` is interpreted since the `multiple symbols defined` error comes from additional declarations of `std::map<Key, size_t>`. This might be a bug in MSVC 16.
2. Fixed some more tests across the repo.
3. Updated the Windows CI to run additional GTSAM tests as well as some `gtsam_unstable` tests.

There is still quite a bit of work to do to get all the tests passing on Windows, but hopefully this is a good start point.

2023-06-29 16:08 UTC, talregev commented
@varunagrawal You asked my help for these tests.
I can help you to compile them, but not run them (make the tests correct). 
I found some bug that I can share with you:
1. On this line: https://github.com/borglab/gtsam/blob/develop/gtsam_unstable/CMakeLists.txt#L111
It should be `GTSAM_EXPORTS` instead of `GTSAM_UNSTABLE_EXPORTS`. There isn't definition for `GTSAM_UNSTABLE_EXPORTS`. I think gtsam_unstable should import/export symbol as gtsam lib.
When I switch it, it make the dll import when compile gtsam_unstable. So the bug is deeper.
2. On this line: https://github.com/borglab/gtsam/blob/develop/gtsam_unstable/CMakeLists.txt#L107
It should be `GTSAM_IMPORT_STATIC` instead GTSAM_UNSTABLE_IMPORT_STATIC. I didn't try it.
I think it also be confuse, and need to investigate more deeply the bug. 
3. On this line https://github.com/borglab/gtsam/blob/develop/gtsam/hybrid/tests/testHybridGaussianFactorGraph.cpp#L46
It should add `#include <numeric>` for handle the compile error: `error C2039: 'iota': is not a member of 'std'`

Good luck to hunt more bugs!

2023-06-30 03:41 UTC, talregev commented
By the way, I am not sure if you notice. Even that the ci pass, some of the tests are not compile with missing symbols.

2023-06-30 03:56 UTC, talregev commented
testBasisFactors.cpp.obj : error LNK2019: unresolved external symbol "class Eigen::Matrix<double,-1,-1,0,-1,-1> __cdecl gtsam::kroneckerProductIdentity(unsigned __int64,class Eigen::Matrix<double,1,-1,1,1,-1> const &)" (?kroneckerProductIdentity@gtsam@@YA?AV?$Matrix@N$0?0$0?0$0A@$0?0$0?0@Eigen@@_KAEBV?$Matrix@N$00$0?0$00$00$0?0@3@@Z) referenced in function "protected: void __cdecl gtsam::Basis<class gtsam::Chebyshev2>::VectorDerivativeFunctor::calculateJacobian(void)" (?calculateJacobian@VectorDerivativeFunctor@?$Basis@VChebyshev2@gtsam@@@gtsam@@IEAAXXZ)

2023-06-30 16:07 UTC, varunagrawal commented
> 1. On this line: [`develop`/gtsam_unstable/CMakeLists.txt#L111](https://github.com/borglab/gtsam/blob/develop/gtsam_unstable/CMakeLists.txt?rgh-link-date=2023-06-29T16%3A08%3A32Z#L111) It should be `GTSAM_EXPORTS` instead of `GTSAM_UNSTABLE_EXPORTS`. There isn't definition for `GTSAM_UNSTABLE_EXPORTS`. I think gtsam_unstable should import/export symbol as gtsam lib. When I switch it, it make the dll import at compilation of gtsam_unstable. Need to investigate more deeply the bug.

`GTSAM_EXPORTS` and `GTSAM_UNSTABLE_EXPORTS` are autogenerated as part of `dllexport.h.in`. So this is not a bug.

> 2. On this line: [`develop`/gtsam_unstable/CMakeLists.txt#L107](https://github.com/borglab/gtsam/blob/develop/gtsam_unstable/CMakeLists.txt?rgh-link-date=2023-06-29T16%3A08%3A32Z#L107) It should be `GTSAM_IMPORT_STATIC` instead GTSAM_UNSTABLE_IMPORT_STATIC. I didn't try it. I think it also do import instead export and need to investigate more deeply the bug.

Same reasoning as above. :)

> 3. On this line [`develop`/gtsam/hybrid/tests/testHybridGaussianFactorGraph.cpp#L46](https://github.com/borglab/gtsam/blob/develop/gtsam/hybrid/tests/testHybridGaussianFactorGraph.cpp?rgh-link-date=2023-06-29T16%3A08%3A32Z#L46) It should add `#include <numeric>` for handle the compile error: `error C2039: 'iota': is not a member of 'std'`

Nice catch!

2023-06-30 16:09 UTC, varunagrawal commented
> By the way, I am not sure if you notice. Even that the ci pass, some of the tests are not compile with missing symbols.

Yup I am aware. That's the reason this PR is still a draf. :)

2023-06-30 16:11 UTC, talregev commented
> `GTSAM_EXPORTS` and `GTSAM_UNSTABLE_EXPORTS` are autogenerated as part of `dllexport.h.in`. So this is not a bug.
> 
> >

@varunagrawal Thank you the explanation. I was doing second review to check, and I understand it my own that it ok. I edit my comment, and leave the original msg with strikes.

2023-07-03 16:20 UTC, talregev commented
@varunagrawal Are you going to continue to work on these? Is it low priority task?

2023-07-27 16:31 UTC, talregev requested changes

2023-07-27 16:31 UTC, talregev commented on gtsam/inference/Ordering.h
>    This& operator+=(KeyVector& keys);
should remove.

2023-07-27 16:31 UTC, talregev commented on gtsam/inference/Ordering.h
>    bool contains(const Key& key) const;
should remove

2023-07-27 18:34 UTC, talregev requested changes

2023-07-27 18:34 UTC, talregev commented on gtsam/inference/Ordering.h
> +  GTSAM_EXPORT
`GTSAM_EXPORT` should removed.

2023-07-27 18:34 UTC, talregev commented on gtsam/inference/Ordering.h
> +  GTSAM_EXPORT
`GTSAM_EXPORT` should removed.

2023-07-27 20:15 UTC, talregev commented on gtsam/discrete/SignatureParser.h
> +#include <gtsam/dllexport.h>
`#include <gtsam/dllexport.h>` should removed. There exactly one there.

2023-07-27 20:16 UTC, talregev commented
After my fix test PR was merge. What fix this PR is aiming for?

2023-07-27 21:19 UTC, varunagrawal commented
A lot of tests in the CI are commented out. We should fix all of them in order to merge this PR.

2023-07-28 07:06 UTC, talregev commented
> A lot of tests in the CI are commented out. We should fix all of them in order to merge this PR.

It should focus on one test fix / one type of problem. Is a bad practice to create a PR that deal with all the problems.
Also what current changes are aim to fix? What problem they are solving?

2023-08-01 14:38 UTC, varunagrawal commented
@talregev @mikesheffler @dellaert I fixed all the `GTSAM` tests for Windows. Only the tests for `GTSAM_UNSTABLE` are left which I will leave for later.

2023-08-01 15:33 UTC, varunagrawal commented
> You should squash the commits. It not recommended to have all these commits and merges to dev branch.

We prefer to keep the history so we can go back and identify bad commits and undo them. This is why we don't squash or force-push.

2023-08-01 15:34 UTC, varunagrawal commented
> @varunagrawal Are you interesting to deal with these errors? ![image](https://user-images.githubusercontent.com/7043539/257563849-1fb832e7-d930-47d9-a6a9-7ad36dcf7a42.png)

Why is it using `gtsamDebug.dll` in the Release config?

2023-08-01 15:35 UTC, talregev commented
> > @varunagrawal Are you interesting to deal with these errors? ![image](https://user-images.githubusercontent.com/7043539/257563849-1fb832e7-d930-47d9-a6a9-7ad36dcf7a42.png)
> 
> Why is it using `gtsamDebug.dll` in the Release config?

This is another bug you have in the cmake when I compile it with vcpkg.
I am not sure what happen in the regular compilation. 

But the debug assertion still happen on your side. Are you interesting to solve it?

2023-08-01 15:37 UTC, varunagrawal commented
> This is another bug you have in the cmake when I compile it with vcpkg. I am not sure what happen in the regular compilation.

I have never had this issue. I have been compiling and debugging using the Release config for the last week and it seems to be fine. Maybe the issue is in your vcpkg settings?

> But the debug assertion still happen on your side. Are you interesting to solve it?

I do not get this error on my end. I re-ran the tests again and they pass without problems.

2023-08-01 15:38 UTC, talregev commented
> I have never had this issue. I have been compiling and debugging using the Release config for the last week and it seems to be fine. Maybe the issue is in your vcpkg settings?

Let's deal with this later. It not for this PR. 

> I do not get this error on my end. I re-ran the tests again and they pass without problems.

Of course there isn't errors. It not enable. I can enable it and you will see these errors.

2023-08-01 15:41 UTC, varunagrawal commented
> Of course there isn't errors. It not enable. I can enable it and you will see these errors.
Sorry I don't understand. What is not enabled?

2023-08-01 15:42 UTC, talregev commented
> Sorry I don't understand. What is not enabled?

The flag that enable the debug assertion that enable extra checks on run time.

2023-08-01 15:43 UTC, varunagrawal commented
Can you please share the changes here? I can run them locally.

2023-08-01 15:46 UTC, talregev commented
I will. It will be later.

2023-08-01 15:47 UTC, varunagrawal commented
> I will. It will be later.

Then can you please approve this PR?

2023-08-01 17:38 UTC, talregev approved these changes

2023-08-02 16:32 UTC, merged