Use METIS system library if so selected
borglab/gtsam pull request #570
Opened 2020-10-19 05:57 UTC by jlblancoc

This addresses the libmetis part of #292.

Defines a new cmake flag `GTSAM_USE_SYSTEM_METIS` (default=off) and uses system libraries in GNU/Linux systems if set to ON. This has been tested with `METISOrderingExample` for both configurations. 

Note: the current CI won't test the GTSAM_USE_SYSTEM_METIS=ON case... 
Perhaps one of the cases in the test matrix should address using all system libraries (Eigen, Metis,...)?

(cc: @berndpfrommer )

2020-10-19 22:29 UTC, acxz reviewed
@jlblancoc 

glad to see you working on this! Had some questions about this though.

Shouldn't https://github.com/borglab/gtsam/blob/develop/gtsam/inference/Ordering.cpp#L28
be changed to just `<metis.h>`
as well as https://github.com/borglab/gtsam/blob/develop/gtsam_unstable/partition/FindSeparator-inl.h#L25 being changed to `<metislib.h>` in this PR?

2020-10-19 22:34 UTC, jlblancoc commented
> @jlblancoc
> 
> glad to see you working on this! Had some questions about this though.
> 
> Shouldn't https://github.com/borglab/gtsam/blob/develop/gtsam/inference/Ordering.cpp#L28
> be changed to just `<metis.h>`
> as well as https://github.com/borglab/gtsam/blob/develop/gtsam_unstable/partition/FindSeparator-inl.h#L25 being changed to `<metislib.h>` in this PR?

Good catch! :+1:

2020-10-19 22:38 UTC, acxz commented
based on my past effort on this task, I fear you might not be able to use `<metislib.h>`. Re: https://github.com/borglab/gtsam/issues/292#issuecomment-656276457

2020-11-18 20:17 UTC, varunagrawal approved these changes
LGTM. I am blown away by your CMake skills @jlblancoc!

2020-11-18 20:20 UTC, varunagrawal commented
We should create an issue for @acxz's comments and tackle them in the next PR. This PR is atomically very nice.

2020-11-18 21:23 UTC, acxz commented
I don't want to be a downer but I don't think this PR should be merged before addressing the issues I have raised.
For one we are still using the older include path which contains the 3rdparty path. This means that even if I am setting the `SYSTEM_METIS` flag to be on, I still won't be using the metis system include file.
Even if that is changed, system metis does not provide `metislib.h` which means we won't be able to use the functionality of it. Thus rendering the `SYSTEM_METIS` flag broken. If its going to be broken when merged in, we should just not merge it in.

2020-11-18 22:35 UTC, varunagrawal commented
Fair point. I'm going to leave this as approved and trust @jlblancoc to add in the updates before we merge.

2020-11-20 00:06 UTC, varunagrawal requested changes
We need to make the changes as recommended by @acxz.

2021-09-18 06:12 UTC, varunagrawal commented
@jlblancoc I'm merging this. 🙂

2021-09-18 06:12 UTC, merged

2021-10-03 20:25 UTC, jlblancoc commented
> Let's merge? @jlblancoc please do the honors.

@varunagrawal  Sorry, I've been busy and missed a *lot* of what's happening here... so glad you guys made it work :-)