IMU Parameters Documentation
borglab/gtsam pull request #624
Opened 2020-12-01 03:42 UTC by varunagrawal

Fixes #213

2020-12-01 04:18 UTC, dellaert commented
Attach a PDF ?

2020-12-01 04:29 UTC, varunagrawal commented
The PDF is attached. It is the last of the 3 files, or am I misreading your comment?

2020-12-01 15:56 UTC, dellaert requested changes
Sorry, but the table about units - which I gather is the only thing you added - does not make sense in this document. I encourage you to read the document (as I did, again, for the review), and then you'll see this table come as a complete surprise. Perhaps this table, which refers to variables in the IMU factor, should go as documentation in the code?

2020-12-01 15:56 UTC, dellaert commented on cmake/GtsamTesting.cmake
> +option(GTSAM_BUILD_TIMING_ALWAYS         "Build timing scripts with 'make all' (build with 'make timing' if not"    OFF)
remove this from diff

2020-12-01 17:03 UTC, varunagrawal commented on cmake/GtsamTesting.cmake
> +option(GTSAM_BUILD_TIMING_ALWAYS         "Build timing scripts with 'make all' (build with 'make timing' if not"    OFF)
Aye aye

2020-12-01 19:25 UTC, dellaert approved these changes
yay!

2020-12-01 19:25 UTC, dellaert commented
Feel free to merge and delete branch after checks passed :-)

2020-12-01 20:59 UTC, varunagrawal commented
Don't you love how unicode lets us put all the math symbols directly in an easy-to-read manner? :D

2020-12-02 00:04 UTC, merged

2020-12-02 09:34 UTC, jlblancoc commented on cmake/GtsamTesting.cmake
> +	option(GTSAM_BUILD_TIMING_ALWAYS         "Build timing scripts with 'make all' (build with 'make timing' if not"    OFF)
oops... :-)

2021-11-26 10:11 UTC, mintar commented
I'm pretty sure that this is incorrect:

```c++
Vector3 biasAcc_; ///< The units for stddev are σ = m/s² or m √Hz/s²
Vector3 biasGyro_; ///< The units for stddev are σ = rad/s or rad √Hz/s
```
It should be:

```c++
Vector3 biasAcc_; ///< The units for stddev are σ = m √Hz/s²
Vector3 biasGyro_; ///< The units for stddev are σ = rad √Hz/s
```

See [my comment here](https://github.com/borglab/gtsam/issues/213#issuecomment-979843896) for an in-depth explanation.

2021-11-26 17:28 UTC, dellaert commented
@varunagrawal if you agree change it?