changed barcsq to a vector to allow each factor to have a different inlier threshold
borglab/gtsam pull request #684
Opened 2021-01-23 02:30 UTC by lucacarlone

I realized that having a default inlier threshold equal to 1 does not make sense for the gtsam user since:
1) "1" is not a reasonable error threshold (for Gaussian noise, we should use the chi2inv to establish a reasonable maximum error) and 
2) the factors can have different dimensions, hence it is desirable to be able to set a different threshold for each factor.

The PR involves:

- [ ] making barcsq into a vector
- [ ] adding/adjusting the unit tests accordingly
- [ ] initializing barcsq using chi2inv

2021-01-23 04:27 UTC, lucacarlone commented
@dellaert @jingnanshi @pantonante : I completed a small enhancement for GNC. please take a look and approve if you like it.

@dellaert : please take a look at the 2 lines commented at line 658 of testGncOptimizer. It seems that "dim()" segfaults when we use the default noise model in the factor. This might be a bug in gtsam.

2021-01-27 14:28 UTC, dellaert approved these changes
Nice! Sorry about delay, teaching large class ;-)

2021-01-27 14:30 UTC, dellaert requested changes
PR is fine, but changing to "request changes" as I just noticed CI fails on Linux. Probably something small but needs to be fixed before we can merge.

2021-01-27 15:08 UTC, dellaert commented
> @dellaert : please take a look at the 2 lines commented at line 658 of testGncOptimizer. It seems that "dim()" segfaults when we use the default noise model in the factor. This might be a bug in gtsam.

Is that why CI fails? Let me check.

2021-01-30 00:08 UTC, lucacarlone commented
@dellaert: let me know if you get some insight into what's failing in CI. I took another pass and cleaned up the comments. @jingnanshi  @pantonante : feel free to approve if this looks good.

2021-01-30 03:00 UTC, jingnanshi commented on gtsam/nonlinear/GncOptimizer.h
> +//#include <boost/math/distributions/inverse_chi_squared.hpp>
We might want to remove this line.

2021-01-30 03:02 UTC, jingnanshi approved these changes
Everything looks good! I left one comment regarding a commented out include file.

2021-01-30 22:04 UTC, lucacarlone commented on gtsam/nonlinear/GncOptimizer.h
> +//#include <boost/math/distributions/inverse_chi_squared.hpp>
good catch - done!

2021-01-30 23:26 UTC, dellaert commented
Still some failures on Ubuntu, though?

2021-01-30 23:28 UTC, lucacarlone commented
@dellaert : I only changed comments so far, I hoped you could look into the dim() issue. Let me know if that's not feasible.

2021-01-31 19:45 UTC, dellaert commented
> @dellaert : I only changed comments so far, I hoped you could look into the dim() issue. Let me know if that's not feasible.

Dim issue is separate, I think. CI failure is unrelated

2021-02-01 00:43 UTC, lucacarlone commented
@dellaert : @jingnanshi fixed the issue! at this point, this branch should be good to go

2021-02-03 18:44 UTC, dellaert approved these changes

2021-02-03 18:44 UTC, merged