fix UnaryFactor jacobian
borglab/gtsam pull request #715
Opened 2021-03-15 12:15 UTC by nmahabadi

* Fix Unaryfactor jacobian in LocalizationExample.cpp.
* Update gtsam document.

2021-03-18 20:20 UTC, varunagrawal commented
@nmahabadi can you please pull the latest `develop` and merge it into this PR?

2021-03-22 07:33 UTC, nmahabadi commented
Hi @varunagrawal, I fetched the latest from develop and rebased this branch to it. 
Let me know if that's okey.

2021-03-22 14:23 UTC, varunagrawal commented
Would have preferred a merge to avoid potential conflicts, but this works. :slightly_smiling_face:

2021-03-22 14:46 UTC, varunagrawal approved these changes
LGTM

@dellaert please take a look when you can.

2021-03-22 14:46 UTC, varunagrawal commented on doc/gtsam.lyx
> +reference "subsec:Full-Posterior-Inference"
Looks good

2021-03-22 21:25 UTC, dellaert requested changes
Many unrelated changes in build files DO NOT MERGE

2021-03-22 21:33 UTC, dellaert commented
I think something went wrong with rebase :-)
Typically, we ask people to *merge* develop into published branches rather than rebase to avoid surprises like this. Could you open a new PR starting from develop, cherry pick your relevant changes?

2021-03-23 08:17 UTC, nmahabadi commented
Ok I will close this PR and open a new one.

2021-03-23 08:17 UTC, closed without merging