Add a MagPoseFactor for using magnetometer measurements with Pose2/Pose3
borglab/gtsam pull request #752
Opened 2021-04-23 14:12 UTC by miloknowles

This PR adds a new `MagPoseFactor<POSE>` which extends the existing `MagFactor` to work with `Pose2` and `Pose3`. The factor also includes an optional `body_P_sensor` in case the magnetometer does not coincide with the body frame. I implemented this factor so that I could use magnetometer measurements within a VIO system, and thought it might be useful to others. It doesn't seem like the `MagFactor` gets much use, so no worries if you don't think this factor should be added.

2021-05-31 16:36 UTC, varunagrawal approved these changes
LGTM

2021-05-31 16:36 UTC, varunagrawal commented on gtsam_unstable/slam/MagPoseFactor.h
> +  typedef MagPoseFactor<POSE> This;
Can you switch from `typedef` to the more modern `using` syntax?

2021-05-31 16:36 UTC, varunagrawal commented on gtsam_unstable/slam/MagPoseFactor.h
> +  typedef typename boost::shared_ptr<MagPoseFactor<POSE>> shared_ptr;
`using` instead of `typedef`?

2021-05-31 16:36 UTC, varunagrawal commented on gtsam_unstable/slam/MagPoseFactor.h
> +  /** Default constructor - only use for serialization. */
Single line docstrings should be triple forward slashes aka `///`

2021-05-31 16:36 UTC, varunagrawal commented on gtsam_unstable/slam/MagPoseFactor.h
> +  /** print */
Triple forward slash

2021-05-31 16:36 UTC, varunagrawal commented on gtsam_unstable/slam/MagPoseFactor.h
> +  /** equals */
Triple forward slash

2021-05-31 16:36 UTC, varunagrawal commented on gtsam_unstable/slam/MagPoseFactor.h
> +  /** Serialization function */
Triple forward slash

2021-05-31 16:36 UTC, varunagrawal commented on gtsam_unstable/slam/MagPoseFactor.h
> +   * @param measurement magnetometer reading, a Point2 or Point3
Should this be `measured` instead of `measurement`?

2021-05-31 16:36 UTC, varunagrawal requested changes
LGTM

2021-05-31 16:36 UTC, varunagrawal requested changes
LGTM

2021-05-31 16:36 UTC, varunagrawal requested changes
LGTM

2021-05-31 16:36 UTC, varunagrawal requested changes
LGTM

2021-05-31 16:36 UTC, varunagrawal requested changes
LGTM

2021-05-31 16:36 UTC, varunagrawal requested changes
LGTM

2021-05-31 16:36 UTC, varunagrawal requested changes
LGTM

2021-05-31 16:36 UTC, varunagrawal requested changes
LGTM

2021-05-31 16:40 UTC, varunagrawal commented
Sorry for the ridiculous amounts of reviews. Github was unresponsive for a while and I have no idea what happened.

2021-05-31 16:41 UTC, varunagrawal commented
@dellaert should we consider moving both `MagFactor` and `MagPoseFactor` from `gtsam_unstable` to `gtsam`?

2021-06-01 20:33 UTC, miloknowles commented
Thanks for the review, @varunagrawal! Made the changes you requested and will wait on the decision about moving out of `gtsam_unstable`.

2021-06-02 16:14 UTC, varunagrawal approved these changes
LGTM

2021-06-03 15:08 UTC, varunagrawal commented
@miloknowles we can always consider moving it out of `gtsam_unstable` in another PR. Let's merge this for now.

2021-06-03 15:09 UTC, merged

2021-06-03 17:22 UTC, tmcg0 commented
Sorry to comment on a closed PR, but glad this got merged! I had actually built a [custom factor](https://github.com/tmcg0/bioslam/blob/dev/include/factors/MagPose3Factor.h) to do this in my own work and this way more robust and tested than the one I had made, so thanks Milo!

I just wanted to throw in my 2 cents that this would be great to move out of `gtsam_unstable`. I'm not sure what determines what goes in unstable vs. not, but I can't think of any major deficiencies with this w.r.t. manifold discontinuities, numerical conditioning, or instability of any subcomponent.

2021-06-03 17:51 UTC, dellaert commented
Awesome. Fork, move, PR :-)

2021-06-03 18:44 UTC, miloknowles commented
@tmcg0 feel free to open the `gtsam_unstable` --> `gtsam` PR if you're already working on it! Otherwise I'm happy to take care of that.

2021-06-03 18:48 UTC, tmcg0 commented
> @tmcg0 feel free to open the `gtsam_unstable` --> `gtsam` PR if you're already working on it! Otherwise I'm happy to take care of that.

You can go ahead and take care of it! I haven't started it and I'm sure I'd mess up something with the build scripts or python bindings and have to spend a lot of time backtracking fixes.